######################################################################
# Automatically generated by qmake (3.0) ?? 5? 4 20:43:40 2015
######################################################################

TEMPLATE = app
TARGET = learning1
INCLUDEPATH += .

# Input
HEADERS += learning1.h GeneratedFiles/ui_learning1.h
FORMS += learning1.ui
SOURCES += learning1.cpp main.cpp GeneratedFiles/qrc_learning1.cpp
RESOURCES += learning1.qrc
