######################################################################
# Automatically generated by qmake (3.0) ?? 8? 10 10:49:14 2015
######################################################################

TEMPLATE = app
TARGET = learning1
INCLUDEPATH += .

# Input
HEADERS += learning1.h GeneratedFiles/ui_learning1.h
FORMS += learning1.ui
SOURCES += 1.1_hello.cpp \
           1.2_quit.cpp \
           1.3_layout.cpp \
           learning1.cpp \
           GeneratedFiles/qrc_learning1.cpp
RESOURCES += learning1.qrc
