######################################################################
# Automatically generated by qmake (3.0) ?? 5? 5 23:19:25 2015
######################################################################

TEMPLATE = app
TARGET = learning2
INCLUDEPATH += .

# Input
HEADERS += 2.1_finddialog.h \
           2.3_gotocelldialog.h \
           learning2.h \
           ui_gotocelldialog.h \
           GeneratedFiles/ui_learning2.h
FORMS += learning2.ui
SOURCES += 2.1_finddialog.cpp \
           2.3_gotocelldialog.cpp \
           learning2.cpp \
           main.cpp \
           GeneratedFiles/qrc_learning2.cpp
RESOURCES += learning2.qrc
