######################################################################
# Automatically generated by qmake (3.0) ?? 5? 5 21:26:28 2015
######################################################################

TEMPLATE = app
TARGET = UI
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
